import { useState } from "react";
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const RandomPicker = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [UserResult, setUserResult] = useState("users");
  const [ProblemResult, setProblemResult] = useState("solve a problem");

  const users = [
    "teachers",
    "students",
    "travellers",
    "sales assistants",
    "workers",
    "citizens",
    "shoppers",
    "gardeners",
    "bee keepers",
    "sports coaches",
    "hairdressers",
    "dog walkers",
    "tattoo artists ",
    "machine operators ",
    "pensioners",
    "pastry chefs",
    "charity workers",
    "plumbers",
    "electricians",
    "mechanical engineers",
    "university professors",
    "travel agents",
    "video game players",
    "voice actors",
    "ethical hackers",
    "blimp pilots",
    "toy designers",
    "sommeliers ",
    "mothers",
    "fathers",
    "runners",
    "swimmers",
    "tennis players",
    "footballers",
    "basketball players"];


  const problems = [
    "complete their taxes",
    "book a holiday",
    "skip the queue at the airport",
    "get a spot on the North Coast 500",
    "fix a bike",
    "plan their pension",
    "commute by bike",
    "plan their week",
    "build a garden shed",
    "order a new phone",
    "find a new job",
    "choose a wedding outfit",
    "send their nan a birthday card",
    "book a morning swimming lane",
    "book a nail appointment",
    "plan a friends birthday party",
    "order pizza for 27 people",
    "open a new bank account",
    "renew their passport",
    "travel to Suffolk ",
    "plan a trip to Glasgow Zoo",
    "sign-up to a gym",
    "create a fire pit",
    "paint their bedroom",
    "fix a pair of broken sunglasses",
    "bake their first ever cake",
    "replace a window",
    "get their motorbike license",
    "grow six sunflowers",
    "tile their bathroom",
    "plan what acts to see at the Edinburgh Fringe Festival",
    "landscape a garden",
    "move bedroom furniture to Lisbon ",
    "dry 5 baskets of laundry ",
    "commute by train",
    "send out baby shower invitations"];

  const handleClick = () => {
    setIsLoading(true);
    const randomUser = users[Math.floor(Math.random() * users.length)];
    const randomProblem =
      problems[Math.floor(Math.random() * problems.length)];

    const userAnimation = setInterval(() => {
      setUserResult(users[Math.floor(Math.random() * users.length)]);
    }, 100);
    const problemAnimation = setInterval(() => {
      setProblemResult(
        problems[Math.floor(Math.random() * problems.length)]
      );
    }, 100);

    setTimeout(() => {
      clearInterval(userAnimation);
      clearInterval(problemAnimation);
      setUserResult(randomUser);
      setProblemResult(randomProblem);
      setIsLoading(false);
    }, 2000);
  };

  return (
    <>
      <Head>
        <title>Idea generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={inter.className}>
            Idea generator
          </div>
        </div>
        <div className={`${styles.center} ${styles.content}`}>
          <h2 className={inter.className}>
            Help{" "}{UserResult}{" "}to{" "}{ProblemResult}
          </h2>
        </div>
        <div className={styles.center}>
          <button className={styles.generateButton} onClick={handleClick} disabled={isLoading}>
            {isLoading ? "Loading..." : "Generate"}
          </button>

        </div>
      </main>
    </>
  );
};

export default RandomPicker;
